---

logging:
  level:
    root: INFO

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/authtestdb?autoReconnect=true&useSSL=false
    username: authtest
    password: authtest
  jpa:
    hibernate.ddl-auto: none
    show_sql: true
